Constitution rewrite
rit-sse/OneRepoToRuleThemAll pull request #358
Opened 2022-03-14 16:32 UTC by 17mgeffert

2022-03-15 15:11 UTC, galenguyer commented on app/markdown/governing-docs/constitution.md
> +harassment, or retaliation, regardless of the offfender's identity or position. It is
Spelling
```suggestion
harassment, or retaliation, regardless of the offender's identity or position. It is
```

2022-03-15 15:11 UTC, galenguyer commented on app/markdown/governing-docs/constitution.md
> +Desicions made by the Primary Officers in regards to the Primary Officer Policy or constitutional interpretation
Spelling
```suggestion
Decisions made by the Primary Officers in regards to the Primary Officer Policy or constitutional interpretation
```

2022-03-15 15:11 UTC, galenguyer commented on app/markdown/governing-docs/constitution.md
> +first have the approval of either two Primary Officers or alternativly, one third of the current Committee Heads
```suggestion
first have the approval of either two Primary Officers or one third of the current Committee Heads 
```

2022-03-16 18:54 UTC, fdeitylink commented on app/markdown/governing-docs/constitution.md
> +view for a public forum allowing optionally anonymous comments. The forum must be
Yeah and it makes it difficult to properly have back and forth conversation/resolution as needed.

2022-03-25 14:21 UTC, fdeitylink commented
Currently, co-op requirement for Committee Heads appears to be stricter than for Primaries. Need to make Primary restriction at least as strict as Committee Head restriction

2022-03-31 19:22 UTC, fdeitylink requested changes
Requesting changes for Removal of Membership and Impeachment clauses to provide for a hearing/way to ensure both sides of the story are considered.

Requesting change for vagueness of Amendment-Only Elections procedures

2022-03-31 19:22 UTC, fdeitylink commented on app/markdown/governing-docs/constitution.md
> +circumstances with a reasonable effort to include the member in the discussion.
This Removal of Membership section has no requirement that a hearing be held in which the member in question can voice their "side of the story" at every step of the process. Hearings should be provided for when probation is being considered, when probation is being evaluated, and when a direct removal of membership is being considered; basically when any relevant decisions are on the table. This is essential to make sure this process is fair.
"reasonable effort" is also vague. It would be useful to clearly specify that outreach is required, perhaps with a timetable (e.g. reach out one week in advance of the hearing and if they do not respond to the outreach, then the officers can hold the discussion without them).

2022-03-31 19:22 UTC, fdeitylink commented on app/markdown/governing-docs/constitution.md
> +in the discussion.
See my earlier comment about Removal of Membership. There need to be similar procedures here and there.

Primary Officer Impeachment is handled very differently but may benefit from a hearing as well. Or a specification that when people are signing the petition, they are presented both sides (from the Officer and from the petitioner).

2022-03-31 19:22 UTC, fdeitylink commented on app/markdown/governing-docs/constitution.md
> +In a semester in which no primary officer positions require an election, and amendments have been proposed in a reasonable timeline, an amendment-only election must be run. The process for this is at
"reasonable timeline" is vague; I think I actually preferred the "ninth week" wording, though you could push it to a later week. It's not necessarily likely but this opens up the potential for abuse if the Primary Officers don't like the amendment and don't want it to be considered. It does seem like the Primary Officers have lots of discretionary powers through the Constitution; if that's how things are generally expected to be, okay..., but I think it's worth pointing out that amendments should maybe be treated specially and outside the discretion of the Primary Officers where possible.
Specifying the process as a whole may be useful as well. Again, PO discretion iffy.
.
Also split this onto multiple lines.

2022-04-06 00:02 UTC, 17mgeffert commented on app/markdown/governing-docs/constitution.md
> -The treasurer is responsible for all financial matters that happen on behalf of the
if you view the current copy it is there, it was removed in a previous commit and readded, i think due to a typo change.

2022-04-06 00:29 UTC, 17mgeffert commented on app/markdown/governing-docs/constitution.md
> +circumstances with a reasonable effort to include the member in the discussion.
Truthfully, this is intentionally left vague to allow the primaries to operate in whatever capacity seems appropriate at the time, as situations like these are usually very complicated and involve heavy oversight from the office anyway. We currently consider membership to be completely determined by the primaries (see "All forms of membership may be contested at any time by the Primary Officers."). I have added an appeals clause to the constitution that provides a level of checks and balances to ensure that primaries do not abuse this power, but honestly I wouldnt feel comfortable implementing a revamp to this process without a lengthy discussion with the officers/ the office. Although I do think their is absolutlely merit in these suggestions, it probably needs to be an entirely seperate conversation/ammendment outside the scope of what this one is trying to accomplish. It should be noted that being on probarionary period still allows you to be a member, and only following the meeting with the member can the membership be revoked, so no desicion can come to pass without a discussion at least being attempted.

2022-04-06 00:35 UTC, 17mgeffert commented on app/markdown/governing-docs/constitution.md
> +in the discussion.
I would have a similar take to my previous comment. In a situation where 2/3rds of all members agree that a person needs to be removed, a hearing is likely not needed. That being said, I am going to add requirments for the petitioner and officer to prepare some sort of "defense" to their argument that must be reviewed by the signing members of the petition as I think that protects from potential biases

2022-04-06 00:58 UTC, 17mgeffert commented on app/markdown/governing-docs/constitution.md
> +In a semester in which no primary officer positions require an election, and amendments have been proposed in a reasonable timeline, an amendment-only election must be run. The process for this is at
yea  i didnt like the week 9 cutoff so thats why  ichanged it, but I can see the issue, i would like to push it to week 10 still which i think makes sense, good catch.

2022-04-06 01:07 UTC, 17mgeffert commented on app/markdown/governing-docs/constitution.md
> +shall begin. Should this not be reached, the candidate shall informed of the
yep in the current version this should be true, long story short i accidently was using an older version of the constituion which had typos from last semester

2022-04-06 03:10 UTC, fdeitylink commented on app/markdown/governing-docs/constitution.md
> +the second highest amount of votes becomming Vice President.
fix typo: becoming

2022-04-06 04:00 UTC, nxb9626 commented on app/markdown/governing-docs/constitution.md
> +delay this process in any way, not can they operate in their position during this time.
this should be 'nor' rather than not

2022-04-06 04:09 UTC, nxb9626 commented on app/markdown/governing-docs/constitution.md
> +The final text for the amendment must be presented in writing to a club advisor
Should this be "club advisor"?

2022-04-20 18:36 UTC, merged